# Generated by Django 4.0.4 on 2022-05-21 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, unique=True)),
                ('latest_price', models.DecimalField(decimal_places=10, max_digits=1000, null=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='base_id', to='assets.asset')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='quote_id', to='assets.asset')),
            ],
        ),
        migrations.CreateModel(
            name='PairPrice',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=10, max_digits=1000)),
                ('ts', models.DateTimeField()),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='assets.pair')),
            ],
        ),
    ]
