name: Dependabot
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  main:
    if: ${{ github.actor == 'dependabot[bot]' }}
    name: Main workflow
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          fetch-depth: 0

      - name: Install and Test
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install -d
          pipenv run python tracker/manage.py test
