# Generated by Django 4.0.4 on 2022-05-21 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=1000)),
                ('price', models.DecimalField(decimal_places=10, max_digits=1000)),
                ('avg_filling_price', models.DecimalField(decimal_places=10, max_digits=1000)),
                ('fee', models.DecimalField(decimal_places=10, max_digits=1000)),
                ('ts', models.DateTimeField()),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.exchange')),
                ('order_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.ordertype')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='assets.pair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Transaction Summary',
                'verbose_name_plural': 'Transactions Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('transactions.transaction',),
        ),
    ]
